# Generated by Django 5.2 on 2025-04-24 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptchaEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captcha_text", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_valid", models.BooleanField(default=True)),
            ],
        ),
    ]
