# Generated by Django 5.0.1 on 2025-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                ("institute_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("no_of_courses", models.IntegerField()),
            ],
        ),
    ]
